Controllers/HomeController.cs
using HFilms.Infrastructure;
using HFilms.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace HFilms.Controllers
{
    public class HomeController : Controller
    {
        private readonly KinoboxApiClient _kinoboxApiClient;


        public HomeController(KinoboxApiClient kinoboxApiClient)
        {
            _kinoboxApiClient = kinoboxApiClient;

        }

        public async Task<IActionResult> Search(string title)
        {
            var films = await _kinoboxApiClient.SearchFilmsAsync(title);

            return RedirectToAction("SearchResults","MovieList" , new { films = films });
        }

        public async Task<IActionResult> Index()
		{
            var popularMovies = await _kinoboxApiClient.GetPopularFilmsAsync();
            return View(popularMovies);
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MovieController.cs
using HFilms.Infrastructure;
using HFilms.Models;
using HFilms.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Web;
using static Azure.Core.HttpHeader;

namespace HFilms.Controllers
{
    public class MovieController : Controller
    {
        private readonly KinoboxApiClient _kinoboxApiClient;
        private readonly UserManager<AppUser> _signInManager;
        private readonly DataContext _dataContext;


        public MovieController(KinoboxApiClient kinoboxApiClient, UserManager<AppUser> signInManager, DataContext dataContext)
        {
            _kinoboxApiClient = kinoboxApiClient;
            _signInManager = signInManager;
            _dataContext = dataContext;
        }

        public async Task<IActionResult> Index()
        {
            var popularMovies = await _kinoboxApiClient.GetPopularFilmsAsync();
            return View(popularMovies);
        }



        public async Task<IActionResult> Search(string title)
        {
            var searchResults = await _kinoboxApiClient.SearchFilmsAsync(title);
            return RedirectToAction("SearchResults", new { title = title });
        }

        public async Task<IActionResult> SearchResults(string title)
        {
            var searchResults = await _kinoboxApiClient.SearchFilmsAsync(title);
            ViewBag.Query = title;
            return View(searchResults);
        }

        public async Task<IActionResult> Details(string kinopoiskId)
        {
            var filmDetails = await _kinoboxApiClient.GetFilmDetailsAsync(kinopoiskId);

           

            if (filmDetails != null)
            {
                return View("Details", filmDetails);
            }
            else
            {
                return View();
            }
        }

		[HttpPost]
		public async Task<IActionResult> SaveSeasonFilms(string KinopoiskId, string nameRu, string season, string seriya, SaveSeason saveSeason)
		{
			// Проверяем, был ли запрос отправлен методом POST
			if (HttpContext.Request.Method == "POST")
			{
				var currentUser = await _signInManager.GetUserAsync(User);

				if (currentUser != null)
				{
					saveSeason.PrimaryTitle = nameRu;
					saveSeason.Seriya = seriya;
					saveSeason.User = currentUser;
					saveSeason.Season = season;
					saveSeason.FilmsID = KinopoiskId;

					_dataContext.SaveSeasons.Add(saveSeason);
					await _dataContext.SaveChangesAsync();
				}
			}

			// Перенаправляем на другую страницу (GET), например, на страницу деталей фильма
			return RedirectToAction("Details", new { kinopoiskId = KinopoiskId });
		}


		public async Task<IActionResult> ViewSeasonFilms()
        {
            return View();
        }



	}
}

Infrastructure/Components/SeriesViewComponent.cs
using HFilms.Controllers;
using HFilms.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HFilms.Infrastructure.Components
{
	public class SeriesViewComponent: ViewComponent
	{
        public async Task<IViewComponentResult> InvokeAsync()
        {
            // Используйте ваш KinoboxApiClient, чтобы получить популярные сериалы
            var kinoboxApiClient = new KinoboxApiClient(new HttpClient());
            var popularSeries = await kinoboxApiClient.GetPopularSeriesAsync();

            // Возвращаем результат
            return View(popularSeries);
        }
    }
}

Views/Home/Index.cshtml
@model List<BasicFilm>
<!-- head -->
<section class="section section--head">
    <div class="container">
        <div class="row">
            <div class="col-12 col-xl-6">
                <h1 class="section__title section__title--head">Популярные фильмы и сериалы</h1>
            </div>

            <div class="col-12 col-xl-6">
                <ul class="breadcrumb">
                    <li class="breadcrumb__item"><a>Главная страница</a></li>
                    <li class="breadcrumb__item"><a>Популярные фильмы и сериалы</a></li>
                </ul>
            </div>
        </div>
    </div>
</section>
<!-- end head -->
<!-- catalog -->
<div class="catalog">
	<div class="container">
		<div class="row">
			<div class="col-12">
                <div class="row row--grid">
                        @foreach (var movie in Model.OrderByDescending(m => m.Id))
                        {
                            @if (!string.IsNullOrEmpty(movie.PosterUrl))
                            {
                                <div class="col-6 col-sm-4 col-lg-3 col-xl-2">
                                    <div class="card">
                                    <a asp-controller="Movie" asp-action="Details" asp-route-kinopoiskId="@movie.Id" class="card__cover">
                                            <img loading="lazy" src="@movie.PosterUrl" style="height: 270px; width: 192px; object-fit: cover;" alt="">
                                            <svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M11 1C16.5228 1 21 5.47716 21 11C21 16.5228 16.5228 21 11 21C5.47716 21 1 16.5228 1 11C1 5.47716 5.47716 1 11 1Z" stroke-linecap="round" stroke-linejoin="round" /><path fill-rule="evenodd" clip-rule="evenodd" d="M14.0501 11.4669C13.3211 12.2529 11.3371 13.5829 10.3221 14.0099C10.1601 14.0779 9.74711 14.2219 9.65811 14.2239C9.46911 14.2299 9.28711 14.1239 9.19911 13.9539C9.16511 13.8879 9.06511 13.4569 9.03311 13.2649C8.93811 12.6809 8.88911 11.7739 8.89011 10.8619C8.88911 9.90489 8.94211 8.95489 9.04811 8.37689C9.07611 8.22089 9.15811 7.86189 9.18211 7.80389C9.22711 7.69589 9.30911 7.61089 9.40811 7.55789C9.48411 7.51689 9.57111 7.49489 9.65811 7.49789C9.74711 7.49989 10.1091 7.62689 10.2331 7.67589C11.2111 8.05589 13.2801 9.43389 14.0401 10.2439C14.1081 10.3169 14.2951 10.5129 14.3261 10.5529C14.3971 10.6429 14.4321 10.7519 14.4321 10.8619C14.4321 10.9639 14.4011 11.0679 14.3371 11.1549C14.3041 11.1999 14.1131 11.3999 14.0501 11.4669Z" stroke-linecap="round" stroke-linejoin="round" /></svg>
                                        </a>
                                    <form method="post" asp-controller="Account" asp-action="AddToFavorites">
                                        <input type="hidden" name="title" value="@movie.PrimaryTitle" />
                                        <input type="hidden" name="posterUrl" value="@movie.PosterUrl" />
                                        <input type="hidden" name="year" value="@movie.Year" />
                                        <input type="hidden" name="id" value="@movie.Id" />
                                        <input type="hidden" name="rating" value="@movie.Rating" />
                                        <input type="hidden" name="filmId" value="@movie.Id" />
                                        <button type="button" class="card__add" onclick="addToFavorites('@movie.PrimaryTitle', '@movie.PosterUrl', '@(movie.Year ?? null)', '@movie.Id' , '@(movie.Rating ?? null)')">
                                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                                <path d="M16,2H8A3,3,0,0,0,5,5V21a1,1,0,0,0,.5.87,1,1,0,0,0,1,0L12,18.69l5.5,3.18A1,1,0,0,0,18,22a1,1,0,0,0,.5-.13A1,1,0,0,0,19,21V5A3,3,0,0,0,16,2Zm1,17.27-4.5-2.6a1,1,0,0,0-1,0L7,19.27V5A1,1,0,0,1,8,4h8a1,1,0,0,1,1,1Z" />
                                            </svg>
                                        </button>
                                    </form>
                                        @if (movie.Rating.HasValue)
                                        {
                                            <span class="card__rating"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M22,9.67A1,1,0,0,0,21.14,9l-5.69-.83L12.9,3a1,1,0,0,0-1.8,0L8.55,8.16,2.86,9a1,1,0,0,0-.81.68,1,1,0,0,0,.25,1l4.13,4-1,5.68A1,1,0,0,0,6.9,21.44L12,18.77l5.1,2.67a.93.93,0,0,0,.46.12,1,1,0,0,0,.59-.19,1,1,0,0,0,.4-1l-1-5.68,4.13-4A1,1,0,0,0,22,9.67Zm-6.15,4a1,1,0,0,0-.29.88l.72,4.2-3.76-2a1.06,1.06,0,0,0-.94,0l-3.76,2,.72-4.2a1,1,0,0,0-.29-.88l-3-3,4.21-.61a1,1,0,0,0,.76-.55L12,5.7l1.88,3.82a1,1,0,0,0,.76.55l4.21.61Z" /></svg> @movie.Rating</span>
                                        }
                                        else
                                        {
                                            <span class="card__rating"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M22,9.67A1,1,0,0,0,21.14,9l-5.69-.83L12.9,3a1,1,0,0,0-1.8,0L8.55,8.16,2.86,9a1,1,0,0,0-.81.68,1,1,0,0,0,.25,1l4.13,4-1,5.68A1,1,0,0,0,6.9,21.44L12,18.77l5.1,2.67a.93.93,0,0,0,.46.12,1,1,0,0,0,.59-.19,1,1,0,0,0,.4-1l-1-5.68,4.13-4A1,1,0,0,0,22,9.67Zm-6.15,4a1,1,0,0,0-.29.88l.72,4.2-3.76-2a1.06,1.06,0,0,0-.94,0l-3.76,2,.72-4.2a1,1,0,0,0-.29-.88l-3-3,4.21-.61a1,1,0,0,0,.76-.55L12,5.7l1.88,3.82a1,1,0,0,0,.76.55l4.21.61Z" /></svg> Неизвестно</span>
                                        }
                                    <h3 class="card__title"><a asp-controller="Movie" asp-action="Details" asp-route-kinopoiskId="@movie.Id">@movie.PrimaryTitle</a></h3>
                                        <ul class="card__list">
                                            <li>HD</li>
                                            <li>Ru/Eng</li>
                                            <li>@movie.Year</li>
                                        </ul>
                                    </div>
                                </div>
                            }
                    }
                    <vc:series></vc:series>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
    function addToFavorites(title, posterUrl, year, Id, rating) {
        // Создайте объект FormData для передачи данных на сервер
        var formData = new FormData();
        formData.append('title', title);
        formData.append('posterUrl', posterUrl);
        formData.append('year', year);
        formData.append('id', Id);
        formData.append('rating', rating);

        // Отправьте запрос на сервер, используя Fetch API
        fetch('/Account/AddToFavorites', {
            method: 'POST',
            body: formData,
            headers: {
                'X-Requested-With': 'XMLHttpRequest' // Укажите, что это AJAX-запрос
            }
        })
            .then(response => {
                if (response.ok) {
                    // Обновите интерфейс или предоставьте обратную связь пользователю
                    console.log('Film added to favorites successfully.');
                } else {
                    console.error('Failed to add film to favorites.');
                }
            })
            .catch(error => {
                console.error('An error occurred while adding film to favorites.', error);
            });
    }
</script>