Models/SearchResult.cs
namespace HFilms.Models
{
    public class SearchResult
    {
        public string Title { get; set; }
        public string PosterUrl { get; set; }
        // Другие необходимые свойства
    }
}

Models/ViewModels/SearchResultsViewModel.cs
namespace HFilms.Models.ViewModels
{
    public class SearchResultsViewModel
    {
        public List<BasicFilm> FilmsAndSeries { get; set; }
    }
}

Controllers/MovieController.cs
using HFilms.Infrastructure;
using HFilms.Models;
using HFilms.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Web;
using static Azure.Core.HttpHeader;

namespace HFilms.Controllers
{
    public class MovieController : Controller
    {
        private readonly KinoboxApiClient _kinoboxApiClient;
        private readonly UserManager<AppUser> _signInManager;
        private readonly DataContext _dataContext;


        public MovieController(KinoboxApiClient kinoboxApiClient, UserManager<AppUser> signInManager, DataContext dataContext)
        {
            _kinoboxApiClient = kinoboxApiClient;
            _signInManager = signInManager;
            _dataContext = dataContext;
        }

        public async Task<IActionResult> Index()
        {
            var popularMovies = await _kinoboxApiClient.GetPopularFilmsAsync();
            return View(popularMovies);
        }



        public async Task<IActionResult> Search(string title)
        {
            var searchResults = await _kinoboxApiClient.SearchFilmsAsync(title);
            return RedirectToAction("SearchResults", new { title = title });
        }

        public async Task<IActionResult> SearchResults(string title)
        {
            var searchResults = await _kinoboxApiClient.SearchFilmsAsync(title);
            ViewBag.Query = title;
            return View(searchResults);
        }

        public async Task<IActionResult> Details(string kinopoiskId)
        {
            var filmDetails = await _kinoboxApiClient.GetFilmDetailsAsync(kinopoiskId);

           

            if (filmDetails != null)
            {
                return View("Details", filmDetails);
            }
            else
            {
                return View();
            }
        }

		[HttpPost]
		public async Task<IActionResult> SaveSeasonFilms(string KinopoiskId, string nameRu, string season, string seriya, SaveSeason saveSeason)
		{
			// Проверяем, был ли запрос отправлен методом POST
			if (HttpContext.Request.Method == "POST")
			{
				var currentUser = await _signInManager.GetUserAsync(User);

				if (currentUser != null)
				{
					saveSeason.PrimaryTitle = nameRu;
					saveSeason.Seriya = seriya;
					saveSeason.User = currentUser;
					saveSeason.Season = season;
					saveSeason.FilmsID = KinopoiskId;

					_dataContext.SaveSeasons.Add(saveSeason);
					await _dataContext.SaveChangesAsync();
				}
			}

			// Перенаправляем на другую страницу (GET), например, на страницу деталей фильма
			return RedirectToAction("Details", new { kinopoiskId = KinopoiskId });
		}


		public async Task<IActionResult> ViewSeasonFilms()
        {
            return View();
        }



	}
}

Infrastructure/Components/SeasonViewComponent.cs
using HFilms.Controllers;
using HFilms.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;

namespace HFilms.Infrastructure.Components
{
	public class SeasonViewComponent : ViewComponent
	{
		private DataContext _context;
		private readonly UserManager<AppUser> _signInManager;
		private readonly DataContext _dataContext;

		public SeasonViewComponent(UserManager<AppUser> signInManager, DataContext dataContext)
        {
			_context = dataContext;
			_signInManager = signInManager;
			_dataContext = dataContext;
		}

		public async Task<IViewComponentResult> InvokeAsync(string kinopoisk)
		{
			var currentUser = await _signInManager.GetUserAsync((System.Security.Claims.ClaimsPrincipal)User);

			if (currentUser == null)
			{
				return View(new List<SaveSeason>());
			}
			var istruePerson = _dataContext.SaveSeasons
				.Where(o => o.UserId == currentUser.Id && o.FilmsID == kinopoisk)
				.ToList();

			return View(istruePerson);
		}
	}
}

Views/Movie/Details.cshtml
@model FilmDetails
<!-- details -->
<section class="section section--head">
	<div class="container">
		<!-- article -->
		<div class="article">
			<div class="row">
				<div class="col-12 col-xl-8">
					<!-- trailer -->
					<!-- end trailer -->
					<!-- article content -->
					<div class="article__content">
						<h1>@Model.nameRu</h1>

						<img loading="lazy" src="@Model.posterUrl" style="height: 350px; width: 250px; object-fit: cover;" alt="">

						<ul class="list">
							<li><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M22,9.67A1,1,0,0,0,21.14,9l-5.69-.83L12.9,3a1,1,0,0,0-1.8,0L8.55,8.16,2.86,9a1,1,0,0,0-.81.68,1,1,0,0,0,.25,1l4.13,4-1,5.68A1,1,0,0,0,6.9,21.44L12,18.77l5.1,2.67a.93.93,0,0,0,.46.12,1,1,0,0,0,.59-.19,1,1,0,0,0,.4-1l-1-5.68,4.13-4A1,1,0,0,0,22,9.67Zm-6.15,4a1,1,0,0,0-.29.88l.72,4.2-3.76-2a1.06,1.06,0,0,0-.94,0l-3.76,2,.72-4.2a1,1,0,0,0-.29-.88l-3-3,4.21-.61a1,1,0,0,0,.76-.55L12,5.7l1.88,3.82a1,1,0,0,0,.76.55l4.21.61Z" /></svg> @Model.ratingKinopoisk</li>
							
							<li>@Model.year</li>
						</ul>
						
						<p>@Model.description</p>
						<p></p>
						<p></p>
						<p></p>


						<div class="col-12">
							<form asp-action="SaveSeasonFilms" asp-controller="Movie" method="post" class="subscribe">
								<div class="subscribe__img">
									<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M13.64,9.74l-.29,1.73A1.55,1.55,0,0,0,14,13a1.46,1.46,0,0,0,1.58.09L17,12.28l1.44.79A1.46,1.46,0,0,0,20,13a1.55,1.55,0,0,0,.63-1.51l-.29-1.73,1.2-1.22a1.54,1.54,0,0,0-.85-2.6l-1.62-.24-.73-1.55a1.5,1.5,0,0,0-2.72,0l-.73,1.55-1.62.24a1.54,1.54,0,0,0-.85,2.6Zm1.83-2.13a1.51,1.51,0,0,0,1.14-.85L17,5.93l.39.83a1.55,1.55,0,0,0,1.14.86l1,.14-.73.74a1.57,1.57,0,0,0-.42,1.34l.16,1-.79-.43a1.48,1.48,0,0,0-1.44,0l-.79.43.16-1a1.54,1.54,0,0,0-.42-1.33l-.73-.75ZM21,15.26a1,1,0,0,0-1,1v3a1,1,0,0,1-1,1H5a1,1,0,0,1-1-1V9.67l5.88,5.88a2.94,2.94,0,0,0,2.1.88l.27,0a1,1,0,0,0,.91-1.08,1,1,0,0,0-1.09-.91.94.94,0,0,1-.77-.28L5.41,8.26H9a1,1,0,0,0,0-2H5a3,3,0,0,0-3,3v10a3,3,0,0,0,3,3H19a3,3,0,0,0,3-3v-3A1,1,0,0,0,21,15.26Z" /></svg>
								</div>
								<h4 class="subscribe__title">Сезон и серия</h4>
								<p class="subscribe__text">Для сохранения сезона и серии - введите их и нажмите "Сохранить"</p>
								<div class="sign__group">
									<input asp-for="Season" class="sign__input" placeholder="Сезон" required >
								</div>

								<div class="sign__group">
									<input asp-for="Seriya" class="sign__input" placeholder="Серия" required>
								</div>
								<div class="sign__group">
									<input asp-for="KinopoiskId" type="hidden" class="sign__input" placeholder="Email">
								</div>
								<div class="sign__group">
									<input asp-for="nameRu" type="hidden" class="sign__input" placeholder="Email">
								</div>

								<button type="submit" class="sign__btn">Сохранить</button>
							</form>
						</div>
						<p></p>
						<p></p>
						<p></p>
						
					</div>
					<!-- end article content -->
				</div>
				
				<div class="col-12 col-xl-8">
					<div class="kinobox_player mx-auto">
						<script src="https://kinobox.tv/kinobox.min.js"></script>
						<script style="position: relative; z-index: 1;">

							var savedTime = localStorage.getItem('videoProgress');

							var kinoboxPlayer = new Kinobox('.kinobox_player', {
								search: {
									kinopoisk: '@Model?.KinopoiskId'
								},
								initialTime: savedTime || 0
							}).init();

						
							kinoboxPlayer.on('timeupdate', function (currentTime) {
								
								localStorage.setItem('videoProgress', currentTime);
							});
						</script>
					</div>
					<div class="article__actions article__actions--details">
						<button type="button" class="article__favorites" onclick="addToFavorites('@Model.nameRu', '@Model.posterUrl', '@(Model.year ?? null)', '@Model.KinopoiskId' , '@(Model.ratingKinopoisk ?? null)')">
							
							<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
								<path d="M16,2H8A3,3,0,0,0,5,5V21a1,1,0,0,0,.5.87,1,1,0,0,0,1,0L12,18.69l5.5,3.18A1,1,0,0,0,18,22a1,1,0,0,0,.5-.13A1,1,0,0,0,19,21V5A3,3,0,0,0,16,2Zm1,17.27-4.5-2.6a1,1,0,0,0-1,0L7,19.27V5A1,1,0,0,1,8,4h8a1,1,0,0,1,1,1Z" />
							</svg>
							Добавить в избранное
						</button>
					</div>
					<p></p>
					<p></p>
					<p></p>
				</div>
				<p></p>
				<p></p>
				<p></p>
				<vc:season kinoPoisk="@Model.KinopoiskId"></vc:season>
				<p></p>
				<p></p>
				<p></p>
				
			</div>
		</div>
		<!-- end article -->
	</div>
</section>

<style>
	/* Стили для вашего верхнего меню */
	.top-menu {
		position: fixed; /* Фиксированное положение */
		top: 0; /* Разместить вверху страницы */
		left: 0; /* Разместить в левом углу */
		width: 100%; /* Занимать всю ширину */
		background-color: #fff; /* Фон верхнего меню */
		z-index: 1000; /* Установить высокий z-index */
	}

	/* Стили для вашего плеера */
	.kinobox_player {
		position: relative; /* Относительное положение */
		z-index: 1; /* Установить z-index меньше, чем у верхнего меню */
	}
</style>
<!-- end details -->

<script>
	function addToFavorites(title, posterUrl, year, Id, rating) {
		// Создайте объект FormData для передачи данных на сервер
		var formData = new FormData();
		formData.append('title', title);
		formData.append('posterUrl', posterUrl);
		formData.append('year', year);
		formData.append('id', Id);
		formData.append('rating', rating);

		// Отправьте запрос на сервер, используя Fetch API
		fetch('/Account/AddToFavorites', {
			method: 'POST',
			body: formData,
			headers: {
				'X-Requested-With': 'XMLHttpRequest' // Укажите, что это AJAX-запрос
			}
		})
			.then(response => {
				if (response.ok) {
					// Обновите интерфейс или предоставьте обратную связь пользователю
					console.log('Film added to favorites successfully.');
				} else {
					console.error('Failed to add film to favorites.');
				}
			})
			.catch(error => {
				console.error('An error occurred while adding film to favorites.', error);
			});
	}
</script>

Views/Movie/Index.cshtml
@model List<BasicFilm>


<!-- head -->
<section class="section section--head">
    <div class="container">
        <div class="row">
            <div class="col-12 col-xl-6">
                <h1 class="section__title section__title--head">Популярные фильмы</h1>
            </div>

            <div class="col-12 col-xl-6">
                <ul class="breadcrumb">
                    <li class="breadcrumb__item"><a asp-controller="Home" asp-action="Index">Домашняя страница</a></li>
                    <li class="breadcrumb__item"><a asp-controller="Movie" asp-action="Index">Популярные фильмы</a></li>
                </ul>
            </div>
        </div>
    </div>
</section>
<!-- end head -->


<div class="catalog catalog--page">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="row row--grid">

                    @foreach (var series in Model.Where(s => !string.IsNullOrEmpty(s.PosterUrl)))
                    {
                        <div class="col-6 col-sm-4 col-lg-3 col-xl-2">
                            <div class="card">
                                <a asp-controller="Movie" asp-action="Details" asp-route-kinopoiskId="@series.Id" class="card__cover">
                                    <img loading="lazy" src="@series.PosterUrl" style="height: 270px; width: 192px; object-fit: cover;" alt="">

                                    <svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M11 1C16.5228 1 21 5.47716 21 11C21 16.5228 16.5228 21 11 21C5.47716 21 1 16.5228 1 11C1 5.47716 5.47716 1 11 1Z" stroke-linecap="round" stroke-linejoin="round" /><path fill-rule="evenodd" clip-rule="evenodd" d="M14.0501 11.4669C13.3211 12.2529 11.3371 13.5829 10.3221 14.0099C10.1601 14.0779 9.74711 14.2219 9.65811 14.2239C9.46911 14.2299 9.28711 14.1239 9.19911 13.9539C9.16511 13.8879 9.06511 13.4569 9.03311 13.2649C8.93811 12.6809 8.88911 11.7739 8.89011 10.8619C8.88911 9.90489 8.94211 8.95489 9.04811 8.37689C9.07611 8.22089 9.15811 7.86189 9.18211 7.80389C9.22711 7.69589 9.30911 7.61089 9.40811 7.55789C9.48411 7.51689 9.57111 7.49489 9.65811 7.49789C9.74711 7.49989 10.1091 7.62689 10.2331 7.67589C11.2111 8.05589 13.2801 9.43389 14.0401 10.2439C14.1081 10.3169 14.2951 10.5129 14.3261 10.5529C14.3971 10.6429 14.4321 10.7519 14.4321 10.8619C14.4321 10.9639 14.4011 11.0679 14.3371 11.1549C14.3041 11.1999 14.1131 11.3999 14.0501 11.4669Z" stroke-linecap="round" stroke-linejoin="round" /></svg>
                                </a>
                                <button type="button" class="card__add" onclick="addToFavorites('@series.PrimaryTitle', '@series.PosterUrl', '@(series.Year ?? 0)', '@series.Id' , '@(series.Rating ?? 0)')">
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                        <path d="M16,2H8A3,3,0,0,0,5,5V21a1,1,0,0,0,.5.87,1,1,0,0,0,1,0L12,18.69l5.5,3.18A1,1,0,0,0,18,22a1,1,0,0,0,.5-.13A1,1,0,0,0,19,21V5A3,3,0,0,0,16,2Zm1,17.27-4.5-2.6a1,1,0,0,0-1,0L7,19.27V5A1,1,0,0,1,8,4h8a1,1,0,0,1,1,1Z" />
                                    </svg>
                                </button>
                                @if (series.Rating.HasValue)
                                {
                                    <span class="card__rating"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M22,9.67A1,1,0,0,0,21.14,9l-5.69-.83L12.9,3a1,1,0,0,0-1.8,0L8.55,8.16,2.86,9a1,1,0,0,0-.81.68,1,1,0,0,0,.25,1l4.13,4-1,5.68A1,1,0,0,0,6.9,21.44L12,18.77l5.1,2.67a.93.93,0,0,0,.46.12,1,1,0,0,0,.59-.19,1,1,0,0,0,.4-1l-1-5.68,4.13-4A1,1,0,0,0,22,9.67Zm-6.15,4a1,1,0,0,0-.29.88l.72,4.2-3.76-2a1.06,1.06,0,0,0-.94,0l-3.76,2,.72-4.2a1,1,0,0,0-.29-.88l-3-3,4.21-.61a1,1,0,0,0,.76-.55L12,5.7l1.88,3.82a1,1,0,0,0,.76.55l4.21.61Z" /></svg> @series.Rating</span>
                                }
                                else
                                {
                                    <span class="card__rating"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M22,9.67A1,1,0,0,0,21.14,9l-5.69-.83L12.9,3a1,1,0,0,0-1.8,0L8.55,8.16,2.86,9a1,1,0,0,0-.81.68,1,1,0,0,0,.25,1l4.13,4-1,5.68A1,1,0,0,0,6.9,21.44L12,18.77l5.1,2.67a.93.93,0,0,0,.46.12,1,1,0,0,0,.59-.19,1,1,0,0,0,.4-1l-1-5.68,4.13-4A1,1,0,0,0,22,9.67Zm-6.15,4a1,1,0,0,0-.29.88l.72,4.2-3.76-2a1.06,1.06,0,0,0-.94,0l-3.76,2,.72-4.2a1,1,0,0,0-.29-.88l-3-3,4.21-.61a1,1,0,0,0,.76-.55L12,5.7l1.88,3.82a1,1,0,0,0,.76.55l4.21.61Z" /></svg> Неизвестно</span>
                                }
                                
                                <h3 class="card__title"><a asp-controller="Movie" asp-action="Details" asp-route-kinopoiskId="@series.Id">@series.PrimaryTitle</a></h3>
                                <ul class="card__list">
                                    <li>HD</li>
                                    <li>Ru/Eng</li>
                                    @if (series.Year.HasValue)
                                    {
                                        <li>@series.Year</li>
                                    }
                                    else
                                    {
                                        <p class="card-text"></p>
                                        <li>Неизвестно</li>
                                    }
                                </ul>
                            </div>
                        </div>
                    }


                    
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function addToFavorites(title, posterUrl, year, Id, rating) {
        // Создайте объект FormData для передачи данных на сервер
        var formData = new FormData();
        formData.append('title', title);
        formData.append('posterUrl', posterUrl);
        formData.append('year', year);
        formData.append('id', Id);
        formData.append('rating', rating);

        // Отправьте запрос на сервер, используя Fetch API
        fetch('/Account/AddToFavorites', {
            method: 'POST',
            body: formData,
            headers: {
                'X-Requested-With': 'XMLHttpRequest' // Укажите, что это AJAX-запрос
            }
        })
            .then(response => {
                if (response.ok) {
                    // Обновите интерфейс или предоставьте обратную связь пользователю
                    console.log('Film added to favorites successfully.');
                } else {
                    console.error('Failed to add film to favorites.');
                }
            })
            .catch(error => {
                console.error('An error occurred while adding film to favorites.', error);
            });
    }
</script>

Views/Movie/SearchResults.cshtml
@model FilmSearchResponse


@if (Model != null)
{
    <!-- head -->
    <section class="section section--head">
        <div class="container">
            <div class="row">
                <div class="col-12 col-xl-6">
                    <h1 class="section__title section__title--head">Поиск</h1>
                </div>

                <div class="col-12 col-xl-6">
                    <ul class="breadcrumb">
                        <li class="breadcrumb__item"><a>Главная страница</a></li>
                        <li class="breadcrumb__item"><a>Поиск</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <!-- end head -->
    <!-- catalog -->
    <div class="catalog">
        <div class="container">
            <div class="row">
                <div class="col-12"> 
                    <div class="row row--grid">
                        @foreach (var movie in Model.films)
                        {
                            if (movie.posterUrl != null && movie.posterUrl != "https://st.kp.yandex.net/images/no-poster.gif" && movie.nameRu != null)
                                    {
                                <div class="col-6 col-sm-4 col-lg-3 col-xl-2">
                                    <div class="card">
                                        <a asp-controller="Movie" asp-action="Details" asp-route-kinopoiskId="@movie.filmId" class="card__cover">
                                            <img loading="lazy" src="@movie.posterUrl"  style="height: 270px; width: 192px; object-fit: cover;" alt="">
                                            <svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M11 1C16.5228 1 21 5.47716 21 11C21 16.5228 16.5228 21 11 21C5.47716 21 1 16.5228 1 11C1 5.47716 5.47716 1 11 1Z" stroke-linecap="round" stroke-linejoin="round" /><path fill-rule="evenodd" clip-rule="evenodd" d="M14.0501 11.4669C13.3211 12.2529 11.3371 13.5829 10.3221 14.0099C10.1601 14.0779 9.74711 14.2219 9.65811 14.2239C9.46911 14.2299 9.28711 14.1239 9.19911 13.9539C9.16511 13.8879 9.06511 13.4569 9.03311 13.2649C8.93811 12.6809 8.88911 11.7739 8.89011 10.8619C8.88911 9.90489 8.94211 8.95489 9.04811 8.37689C9.07611 8.22089 9.15811 7.86189 9.18211 7.80389C9.22711 7.69589 9.30911 7.61089 9.40811 7.55789C9.48411 7.51689 9.57111 7.49489 9.65811 7.49789C9.74711 7.49989 10.1091 7.62689 10.2331 7.67589C11.2111 8.05589 13.2801 9.43389 14.0401 10.2439C14.1081 10.3169 14.2951 10.5129 14.3261 10.5529C14.3971 10.6429 14.4321 10.7519 14.4321 10.8619C14.4321 10.9639 14.4011 11.0679 14.3371 11.1549C14.3041 11.1999 14.1131 11.3999 14.0501 11.4669Z" stroke-linecap="round" stroke-linejoin="round" /></svg>
                                        </a>
                                        <button type="button" class="card__add" onclick="addToFavorites('@Html.Raw(System.Web.HttpUtility.HtmlDecode(movie.nameRu))', '@movie.posterUrl', '@Html.Raw(System.Web.HttpUtility.HtmlDecode(movie.year))', '@movie.filmId' , '@(movie.rating ?? null)')">
                                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                                <path d="M16,2H8A3,3,0,0,0,5,5V21a1,1,0,0,0,.5.87,1,1,0,0,0,1,0L12,18.69l5.5,3.18A1,1,0,0,0,18,22a1,1,0,0,0,.5-.13A1,1,0,0,0,19,21V5A3,3,0,0,0,16,2Zm1,17.27-4.5-2.6a1,1,0,0,0-1,0L7,19.27V5A1,1,0,0,1,8,4h8a1,1,0,0,1,1,1Z" />
                                            </svg>
                                        </button>
                                        @if (movie.rating != null)
                                        {
                                            <span class="card__rating"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M22,9.67A1,1,0,0,0,21.14,9l-5.69-.83L12.9,3a1,1,0,0,0-1.8,0L8.55,8.16,2.86,9a1,1,0,0,0-.81.68,1,1,0,0,0,.25,1l4.13,4-1,5.68A1,1,0,0,0,6.9,21.44L12,18.77l5.1,2.67a.93.93,0,0,0,.46.12,1,1,0,0,0,.59-.19,1,1,0,0,0,.4-1l-1-5.68,4.13-4A1,1,0,0,0,22,9.67Zm-6.15,4a1,1,0,0,0-.29.88l.72,4.2-3.76-2a1.06,1.06,0,0,0-.94,0l-3.76,2,.72-4.2a1,1,0,0,0-.29-.88l-3-3,4.21-.61a1,1,0,0,0,.76-.55L12,5.7l1.88,3.82a1,1,0,0,0,.76.55l4.21.61Z" /></svg> @movie.rating</span>
                                        }
                                        else
                                        {
                                            <span class="card__rating"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M22,9.67A1,1,0,0,0,21.14,9l-5.69-.83L12.9,3a1,1,0,0,0-1.8,0L8.55,8.16,2.86,9a1,1,0,0,0-.81.68,1,1,0,0,0,.25,1l4.13,4-1,5.68A1,1,0,0,0,6.9,21.44L12,18.77l5.1,2.67a.93.93,0,0,0,.46.12,1,1,0,0,0,.59-.19,1,1,0,0,0,.4-1l-1-5.68,4.13-4A1,1,0,0,0,22,9.67Zm-6.15,4a1,1,0,0,0-.29.88l.72,4.2-3.76-2a1.06,1.06,0,0,0-.94,0l-3.76,2,.72-4.2a1,1,0,0,0-.29-.88l-3-3,4.21-.61a1,1,0,0,0,.76-.55L12,5.7l1.88,3.82a1,1,0,0,0,.76.55l4.21.61Z" /></svg> Неизвестно</span>
                                        }
                                        <h3 class="card__title"><a asp-controller="Movie" asp-action="Details" asp-route-kinopoiskId="@movie.filmId">@Html.Raw(System.Web.HttpUtility.HtmlDecode(movie.nameRu))</a></h3>
                                        <ul class="card__list">
                                            <li>HD</li>
                                            <li>Ru/Eng</li>
                                            <li>@Html.Raw(System.Web.HttpUtility.HtmlDecode(movie.year))</li>
                                        </ul>
                                    </div>
                                </div>
                            }
                            else
                            {
                                
                            }

                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script>
    function addToFavorites(title, posterUrl, year, Id, rating) {
        // Создайте объект FormData для передачи данных на сервер
        var formData = new FormData();
        formData.append('title', title);
        formData.append('posterUrl', posterUrl);
        formData.append('year', year);
        formData.append('id', Id);
        formData.append('rating', rating);

        // Отправьте запрос на сервер, используя Fetch API
        fetch('/Account/AddToFavorites', {
            method: 'POST',
            body: formData,
            headers: {
                'X-Requested-With': 'XMLHttpRequest' // Укажите, что это AJAX-запрос
            }
        })
            .then(response => {
                if (response.ok) {
                    // Обновите интерфейс или предоставьте обратную связь пользователю
                    console.log('Film added to favorites successfully.');
                } else {
                    console.error('Failed to add film to favorites.');
                }
            })
            .catch(error => {
                console.error('An error occurred while adding film to favorites.', error);
            });
    }
</script>